services:
  - type: web
    name: scadapres
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn scadapres.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "scadapres.onrender.com"
